/*****************************************************************************
 * Copyright (C) 2016 MediaTek Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 * See http://www.gnu.org/licenses/gpl-2.0.html for more details.
 *
 * Accelerometer Sensor Driver
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 *
 *****************************************************************************/

#ifndef __HWTCON_REG_H__
#define __HWTCON_REG_H__

#include "../hwtcon_driver.h"

/* mmsys top */
#define MMSYS_SW1_RST_B            (hwtcon_device_info()->mmsys_reg_pa + 0x0144)
#define MMSYS_SW1_RST_B_VA         (hwtcon_device_info()->mmsys_reg_va + 0x0144)

/* pipelien reg */
#define PAPER_TCTOP_PWDC_CTL       (hwtcon_device_info()->mmsys_reg_pa + 0xD000)
#define PAPER_TCTOP_MAIN_CTL       (hwtcon_device_info()->mmsys_reg_pa + 0xD004)
#define PAPER_TCTOP_INI_CFG        (hwtcon_device_info()->mmsys_reg_pa + 0xD008)
#define PAPER_TCTOP_PANEL_SIZE     (hwtcon_device_info()->mmsys_reg_pa + 0xD00C)
#define PAPER_TCTOP_REGAL_CFG      (hwtcon_device_info()->mmsys_reg_pa + 0xD010)
#define PAPET_TCTOP_FIFO_CFG       (hwtcon_device_info()->mmsys_reg_pa + 0xD014)
#define PAPER_TCTOP_DPI_CFG        (hwtcon_device_info()->mmsys_reg_pa + 0xD018)
#define PAPER_TCTOP_TCON_POS_CFG   (hwtcon_device_info()->mmsys_reg_pa + 0xD01C)
#define PAPER_TCTOP_UPD_CFG0       (hwtcon_device_info()->mmsys_reg_pa + 0xD020)
#define PAPER_TCTOP_UPD_CFG1       (hwtcon_device_info()->mmsys_reg_pa + 0xD024)
#define PAPER_TCTOP_UPD_CFG2       (hwtcon_device_info()->mmsys_reg_pa + 0xD028)
#define PAPER_TCTOP_UPD_CFG3       (hwtcon_device_info()->mmsys_reg_pa + 0xD02C)
#define PAPER_TCTOP_UPD_CFG4       (hwtcon_device_info()->mmsys_reg_pa + 0xD030)
#define PAPER_TCTOP_VOID_LUT       (hwtcon_device_info()->mmsys_reg_pa + 0xD034)
#define PAPER_TCTOP_SOF_CTL        (hwtcon_device_info()->mmsys_reg_pa + 0xD040)
#define PAPER_TCTOP_IRQ_CTL        (hwtcon_device_info()->mmsys_reg_pa + 0xD044)
#define PAPER_TCTOP_SOF_MERGE_CTL  (hwtcon_device_info()->mmsys_reg_pa + 0xD048)
#define PAPER_TCTOP_SOF_WF_LUT_CTL (hwtcon_device_info()->mmsys_reg_pa + 0xD04C)
#define PAPER_TCTOP_IMG_POS0       (hwtcon_device_info()->mmsys_reg_pa + 0xD050)
#define PAPER_TCTOP_IMG_POS1       (hwtcon_device_info()->mmsys_reg_pa + 0xD054)
#define PAPER_TCTOP_IMG_ID         (hwtcon_device_info()->mmsys_reg_pa + 0xD058)
#define PAPER_TCTOP_BUF_CFG0       (hwtcon_device_info()->mmsys_reg_pa + 0xD060)
#define PAPER_TCTOP_BUF_CFG1       (hwtcon_device_info()->mmsys_reg_pa + 0xD064)
#define PAPER_TCTOP_HIST_CFG0      (hwtcon_device_info()->mmsys_reg_pa + 0xD070)
#define PAPER_TCTOP_HIST_CFG1      (hwtcon_device_info()->mmsys_reg_pa + 0xD074)
#define PAPER_TCTOP_HIST_CFG2      (hwtcon_device_info()->mmsys_reg_pa + 0xD078)
#define PAPER_TCTOP_HIST_CFG3      (hwtcon_device_info()->mmsys_reg_pa + 0xD07C)
#define PAPER_TCTOP_HIST_CFG4      (hwtcon_device_info()->mmsys_reg_pa + 0xD080)
#define PAPER_TCTOP_HIST_STA0      (hwtcon_device_info()->mmsys_reg_pa + 0xD084)
#define PAPER_TCTOP_HIST_STA1      (hwtcon_device_info()->mmsys_reg_pa + 0xD088)
#define PAPER_TCTOP_HIST_STA2      (hwtcon_device_info()->mmsys_reg_pa + 0xD08C)
#define PAPER_TCTOP_STATUS         (hwtcon_device_info()->mmsys_reg_pa + 0xD090)
#define PAPER_UPD_IMG_STA0         (hwtcon_device_info()->mmsys_reg_pa + 0xD094)
#define PAPER_UPD_IMG_STA1         (hwtcon_device_info()->mmsys_reg_pa + 0xD098)
#define PAPER_TCTOP_PIN_SWAP0      (hwtcon_device_info()->mmsys_reg_pa + 0xD0A0)
#define PAPER_TCTOP_PIN_SWAP1      (hwtcon_device_info()->mmsys_reg_pa + 0xD0A4)
#define PAPER_TCTOP_PIN_SWAP2      (hwtcon_device_info()->mmsys_reg_pa + 0xD0A8)
#define PAPER_TCTOP_PIN_SWAP3      (hwtcon_device_info()->mmsys_reg_pa + 0xD0AC)
#define PAPER_TCTOP_PIN_SWAP4      (hwtcon_device_info()->mmsys_reg_pa + 0xD0B0)
#define PAPER_TCTOP_PIN_SWAP5      (hwtcon_device_info()->mmsys_reg_pa + 0xD0B4)
#define PAPER_TCTOP_PIN_INV        (hwtcon_device_info()->mmsys_reg_pa + 0xD0B8)
#define PAPER_TCTOP_WB_BUF_XY_INFO (hwtcon_device_info()->mmsys_reg_pa + 0xD0C4)
#define PAPER_TCTOP_WB_BUF_WH_INFO (hwtcon_device_info()->mmsys_reg_pa + 0xD0C8)
#define PAPER_TCTOP_LUT_ACTIVE0    (hwtcon_device_info()->mmsys_reg_pa + 0xD0D0)
#define PAPER_TCTOP_LUT_ACTIVE1    (hwtcon_device_info()->mmsys_reg_pa + 0xD0D4)
#define PAPER_TCTOP_COL_STATUS0    (hwtcon_device_info()->mmsys_reg_pa + 0xD0D8)
#define PAPER_TCTOP_COL_STATUS1    (hwtcon_device_info()->mmsys_reg_pa + 0xD0DC)
#define PAPER_TCTOP_PXL_UPD_RGN0   (hwtcon_device_info()->mmsys_reg_pa + 0xD0E0)
#define PAPER_TCTOP_PXL_UPD_RGN1   (hwtcon_device_info()->mmsys_reg_pa + 0xD0E4)
#define PAPER_TCTOP_PXL_COL_RGN0   (hwtcon_device_info()->mmsys_reg_pa + 0xD0E8)
#define PAPER_TCTOP_PXL_COL_RGN1   (hwtcon_device_info()->mmsys_reg_pa + 0xD0EC)
#define PAPER_TCTOP_WB_ST_ADDR0    (hwtcon_device_info()->mmsys_reg_pa + 0xDF00)
#define PAPER_TCTOP_WB_ST_ADDR1    (hwtcon_device_info()->mmsys_reg_pa + 0xDF04)
#define PAPER_TCTOP_IMG_ST_ADDR    (hwtcon_device_info()->mmsys_reg_pa + 0xDF08)
#define PIPELINE_FLAG              (hwtcon_device_info()->mmsys_reg_pa + 0xDF0C)

/* IMG_RDMA */
#define IMG_RDMA_GLOBAL_CON        (hwtcon_device_info()->mmsys_reg_pa + 0x8010)
#define IMG_RDMA_GMC_SETTING_0     (hwtcon_device_info()->mmsys_reg_pa + 0x8030)
#define IMG_RDMA_FIFO_CON          (hwtcon_device_info()->mmsys_reg_pa + 0x8040)


/* WB RDMA */
#define WB_RDMA_GLOBAL_CON         (hwtcon_device_info()->mmsys_reg_pa + 0x9010)
#define WB_RDMA_GMC_SETTING_0      (hwtcon_device_info()->mmsys_reg_pa + 0x9030)
#define WB_RDMA_FIFO_CON           (hwtcon_device_info()->mmsys_reg_pa + 0x9040)


/* WB_WDMA */
#define WB_WDMA_INTEN              (hwtcon_device_info()->mmsys_reg_pa + 0xA000)
#define WB_WDMA_INTSTA             (hwtcon_device_info()->mmsys_reg_pa + 0xA004)
#define WB_WDMA_EN                 (hwtcon_device_info()->mmsys_reg_pa + 0xA008)
#define WB_WDMA_RST                (hwtcon_device_info()->mmsys_reg_pa + 0xA00C)
#define WB_WDMA_CFG                (hwtcon_device_info()->mmsys_reg_pa + 0xA014)
#define WB_WDMA_BUF_CON1           (hwtcon_device_info()->mmsys_reg_pa + 0xA038)

/* WF_LUT */
#define WF_LUT_STA                 (hwtcon_device_info()->mmsys_reg_pa + 0x4000)
#define WF_LUT_INTEN               (hwtcon_device_info()->mmsys_reg_pa + 0x4004)
#define WF_LUT_INTSTA              (hwtcon_device_info()->mmsys_reg_pa + 0x4008)
#define WF_LUT_EN                  (hwtcon_device_info()->mmsys_reg_pa + 0x400C)
#define WF_LUT_TRIG                (hwtcon_device_info()->mmsys_reg_pa + 0x4010)
#define WF_LUT_RST                 (hwtcon_device_info()->mmsys_reg_pa + 0x4014)
#define WF_LUT_ROI_SIZE            (hwtcon_device_info()->mmsys_reg_pa + 0x4020)
#define WF_LUT_DATAPATH_CON        (hwtcon_device_info()->mmsys_reg_pa + 0x4024)
#define WF_LUT_SRC_CON             (hwtcon_device_info()->mmsys_reg_pa + 0x402C)
#define WF_LUT_L0_CON              (hwtcon_device_info()->mmsys_reg_pa + 0x4030)
#define WF_LUT_L0_SRC_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4038)
#define WF_LUT_L0_OFFSET           (hwtcon_device_info()->mmsys_reg_pa + 0x403C)
#define WF_LUT_L0_ADDR             (hwtcon_device_info()->mmsys_reg_pa + 0x4F40)
#define WF_LUT_L0_PITCH            (hwtcon_device_info()->mmsys_reg_pa + 0x4044)
#define WF_LUT_L1_CON              (hwtcon_device_info()->mmsys_reg_pa + 0x4050)
#define WF_LUT_L1_SRC_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4058)
#define WF_LUT_L1_OFFSET           (hwtcon_device_info()->mmsys_reg_pa + 0x405c)
#define WF_LUT_L1_ADDR             (hwtcon_device_info()->mmsys_reg_pa + 0x4F60)
#define WF_LUT_L1_PITCH            (hwtcon_device_info()->mmsys_reg_pa + 0x4064)
#define WF_LUT_L2_CON              (hwtcon_device_info()->mmsys_reg_pa + 0x4070)
#define WF_LUT_L2_SRC_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4078)
#define WF_LUT_L2_OFFSET           (hwtcon_device_info()->mmsys_reg_pa + 0x407c)
#define WF_LUT_L2_ADDR             (hwtcon_device_info()->mmsys_reg_pa + 0x4F80)
#define WF_LUT_L2_PITCH            (hwtcon_device_info()->mmsys_reg_pa + 0x4084)
#define WF_LUT_L3_CON              (hwtcon_device_info()->mmsys_reg_pa + 0x4090)
#define WF_LUT_L3_SRC_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4098)
#define WF_LUT_L3_OFFSET           (hwtcon_device_info()->mmsys_reg_pa + 0x409C)
#define WF_LUT_L3_ADDR             (hwtcon_device_info()->mmsys_reg_pa + 0x4FA0)
#define WF_LUT_L3_PITCH            (hwtcon_device_info()->mmsys_reg_pa + 0x40A4)
#define WF_LUT_RDMA0_CTRL          (hwtcon_device_info()->mmsys_reg_pa + 0x40C0)
#define WF_LUT_RDMA0_MEM_GMC_SETTING1 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x40C8)
#define WF_LUT_RDMA0_MEM_SLOW_CON  (hwtcon_device_info()->mmsys_reg_pa + 0x40CC)
#define WF_LUT_RDMA0_FIFO_CTRL     (hwtcon_device_info()->mmsys_reg_pa + 0x40D0)
#define WF_LUT_RDMA1_CTRL          (hwtcon_device_info()->mmsys_reg_pa + 0x40E0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING1 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x40E8)
#define WF_LUT_RDMA1_MEM_SLOW_CON  (hwtcon_device_info()->mmsys_reg_pa + 0x40EC)
#define WF_LUT_RDMA1_FIFO_CTRL     (hwtcon_device_info()->mmsys_reg_pa + 0x40F0)
#define WF_LUT_RDMA2_CTRL          (hwtcon_device_info()->mmsys_reg_pa + 0x4100)
#define WF_LUT_RDMA2_MEM_GMC_SETTING1 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x4108)
#define WF_LUT_RDMA2_MEM_SLOW_CON  (hwtcon_device_info()->mmsys_reg_pa + 0x410C)
#define WF_LUT_RDMA2_FIFO_CTRL     (hwtcon_device_info()->mmsys_reg_pa + 0x4110)
#define WF_LUT_RDMA3_CTRL          (hwtcon_device_info()->mmsys_reg_pa + 0x4120)
#define WF_LUT_RDMA3_MEM_GMC_SETTING1 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x4128)
#define WF_LUT_RDMA3_MEM_SLOW_CON  (hwtcon_device_info()->mmsys_reg_pa + 0x412C)
#define WF_LUT_RDMA3_FIFO_CTRL     (hwtcon_device_info()->mmsys_reg_pa + 0x4130)
#define WF_LUT_DEBUG_MON_SEL       (hwtcon_device_info()->mmsys_reg_pa + 0x41D4)
#define WF_LUT_RDMA0_MEM_GMC_SETTING2 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x41E0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING2 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x41E4)
#define WF_LUT_RDMA2_MEM_GMC_SETTING2 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x41E8)
#define WF_LUT_RDMA3_MEM_GMC_SETTING2 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x41EC)
#define WF_LUT_DUMMY_REG           (hwtcon_device_info()->mmsys_reg_pa + 0x4200)
#define WF_LUT_FLOW_CTRL_DBG       (hwtcon_device_info()->mmsys_reg_pa + 0x4240)
#define WF_LUT_ADDCON_DBG          (hwtcon_device_info()->mmsys_reg_pa + 0x4244)
#define WF_LUT_RDMA0_DBG           (hwtcon_device_info()->mmsys_reg_pa + 0x424C)
#define WF_LUT_RDMA1_DBG           (hwtcon_device_info()->mmsys_reg_pa + 0x4250)
#define WF_LUT_RDMA2_DBG           (hwtcon_device_info()->mmsys_reg_pa + 0x4254)
#define WF_LUT_RDMA3_DBG           (hwtcon_device_info()->mmsys_reg_pa + 0x4258)
#define WF_LUT_EN_STA0             (hwtcon_device_info()->mmsys_reg_pa + 0x4270)
#define WF_LUT_EN_STA1             (hwtcon_device_info()->mmsys_reg_pa + 0x4274)

#define WF_LUT_CRC_0               (hwtcon_device_info()->mmsys_reg_pa + 0x4280)
#define WF_LUT_CRC_1               (hwtcon_device_info()->mmsys_reg_pa + 0x4284)
#define WF_LUT_CRC_2               (hwtcon_device_info()->mmsys_reg_pa + 0x4288)
#define WF_LUT_CRC_3               (hwtcon_device_info()->mmsys_reg_pa + 0x428C)
#define WF_LUT_CRC_4               (hwtcon_device_info()->mmsys_reg_pa + 0x4290)
#define WF_LUT_CRC_5               (hwtcon_device_info()->mmsys_reg_pa + 0x4294)
#define WF_LUT_CRC_6               (hwtcon_device_info()->mmsys_reg_pa + 0x4298)
#define WF_LUT_CRC_7               (hwtcon_device_info()->mmsys_reg_pa + 0x429C)


#define WF_LUT_CRC_0_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4280)
#define WF_LUT_CRC_1_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4284)
#define WF_LUT_CRC_2_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4288)
#define WF_LUT_CRC_3_VA            (hwtcon_device_info()->mmsys_reg_va + 0x428C)
#define WF_LUT_CRC_4_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4290)
#define WF_LUT_CRC_5_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4294)
#define WF_LUT_CRC_6_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4298)
#define WF_LUT_CRC_7_VA            (hwtcon_device_info()->mmsys_reg_va + 0x429C)


#define WF_LUT_SECURE              (hwtcon_device_info()->mmsys_reg_pa + 0x4FC0)
#define WF_LUT_GREQ_LAYER_CNT      (hwtcon_device_info()->mmsys_reg_pa + 0x4234)
#define WF_LUT_SMI_DBG             (hwtcon_device_info()->mmsys_reg_pa + 0x4230)
#define WF_LUT_00_XY_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4400)
#define WF_LUT_00_WH_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4404)
#define WF_LUT_00_ID_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4408)
#define WF_LUT_01_XY_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4410)
#define WF_LUT_01_WH_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4414)
#define WF_LUT_01_ID_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4418)
#define WF_LUT_63_XY_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4700)
#define WF_LUT_63_WH_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4704)
#define WF_LUT_63_ID_INFO          (hwtcon_device_info()->mmsys_reg_pa + 0x4708)
#define WF_LUT_DUAL_MODE           (hwtcon_device_info()->mmsys_reg_pa + 0x4D00)
#define WF_LUT_EN_0                (hwtcon_device_info()->mmsys_reg_pa + 0x4D04)
#define WF_LUT_EN_1                (hwtcon_device_info()->mmsys_reg_pa + 0x4D08)
#define WF_LUT_CON                 (hwtcon_device_info()->mmsys_reg_pa + 0x4D0C)
#define WF_LUT_SHADOW_UP           (hwtcon_device_info()->mmsys_reg_pa + 0x4204)
#define WF_LUT_LEN_0               (hwtcon_device_info()->mmsys_reg_pa + 0x4D10)
#define WF_LUT_LEN_1               (hwtcon_device_info()->mmsys_reg_pa + 0x4D14)
#define WF_LUT_LEN_2               (hwtcon_device_info()->mmsys_reg_pa + 0x4D18)
#define WF_LUT_LEN_3               (hwtcon_device_info()->mmsys_reg_pa + 0x4D1C)
#define WF_LUT_LEN_4               (hwtcon_device_info()->mmsys_reg_pa + 0x4D20)
#define WF_LUT_LEN_5               (hwtcon_device_info()->mmsys_reg_pa + 0x4D24)
#define WF_LUT_LEN_6               (hwtcon_device_info()->mmsys_reg_pa + 0x4D28)
#define WF_LUT_LEN_7               (hwtcon_device_info()->mmsys_reg_pa + 0x4D2C)
#define WF_LUT_LEN_8               (hwtcon_device_info()->mmsys_reg_pa + 0x4D30)
#define WF_LUT_LEN_9               (hwtcon_device_info()->mmsys_reg_pa + 0x4D34)
#define WF_LUT_LEN_10              (hwtcon_device_info()->mmsys_reg_pa + 0x4D38)
#define WF_LUT_LEN_11              (hwtcon_device_info()->mmsys_reg_pa + 0x4D3C)
#define WF_LUT_LEN_12              (hwtcon_device_info()->mmsys_reg_pa + 0x4D40)
#define WF_LUT_LEN_13              (hwtcon_device_info()->mmsys_reg_pa + 0x4D44)
#define WF_LUT_LEN_14              (hwtcon_device_info()->mmsys_reg_pa + 0x4D48)
#define WF_LUT_LEN_15              (hwtcon_device_info()->mmsys_reg_pa + 0x4D4C)
#define WF_LUT_END_IRQ_CLR0        (hwtcon_device_info()->mmsys_reg_pa + 0x4D50)
#define WF_LUT_END_IRQ_CLR1        (hwtcon_device_info()->mmsys_reg_pa + 0x4D54)
#define WF_LUT_END_IRQ_STA0        (hwtcon_device_info()->mmsys_reg_pa + 0x4D58)
#define WF_LUT_END_IRQ_STA1        (hwtcon_device_info()->mmsys_reg_pa + 0x4D5C)
#define WF_LUT_CHKSUM_0            (hwtcon_device_info()->mmsys_reg_pa + 0x4D70)
#define WF_LUT_CHKSUM_1            (hwtcon_device_info()->mmsys_reg_pa + 0x4D74)
#define WF_LUT_CHKSUM_2            (hwtcon_device_info()->mmsys_reg_pa + 0x4D78)
#define WF_LUT_CHKSUM_3            (hwtcon_device_info()->mmsys_reg_pa + 0x4D7C)
#define WF_LUT_CHKSUM_4            (hwtcon_device_info()->mmsys_reg_pa + 0x4D80)
#define WF_LUT_LINK_MODE           (hwtcon_device_info()->mmsys_reg_pa + 0x4D84)
#define WF_LUT_TIMEOUT_CFG         (hwtcon_device_info()->mmsys_reg_pa + 0x4D88)
#define WF_LUT_DEBUG_SRAM          (hwtcon_device_info()->mmsys_reg_pa + 0x4D8C)
#define WF_LUT_MERGE0_START        (hwtcon_device_info()->mmsys_reg_pa + 0x4D90)
#define WF_LUT_MERGE0_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4D94)
#define WF_LUT_MERGE1_START        (hwtcon_device_info()->mmsys_reg_pa + 0x4D98)
#define WF_LUT_MERGE1_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4D9C)
#define WF_LUT_MERGE2_START        (hwtcon_device_info()->mmsys_reg_pa + 0x4DA0)
#define WF_LUT_MERGE2_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4DA4)
#define WF_LUT_MERGE3_START        (hwtcon_device_info()->mmsys_reg_pa + 0x4DA8)
#define WF_LUT_MERGE3_SIZE         (hwtcon_device_info()->mmsys_reg_pa + 0x4DAC)
#define WF_LUT_MERGE_POS_0         (hwtcon_device_info()->mmsys_reg_pa + 0x4DB0)
#define WF_LUT_MERGE_POS_1         (hwtcon_device_info()->mmsys_reg_pa + 0x4DB4)
#define WF_LUT_INFO_XY_CFG         (hwtcon_device_info()->mmsys_reg_pa + 0x4DC0)
#define WF_LUT_INFO_WH_CFG         (hwtcon_device_info()->mmsys_reg_pa + 0x4DC4)
#define WF_LUT_INFO_ID_CFG         (hwtcon_device_info()->mmsys_reg_pa + 0x4DC8)
#define WF_LUT_LINK_BASE_ADDR      (hwtcon_device_info()->mmsys_reg_pa + 0x4F00)
#define WF_LUT_LINK_BASE_ADDR_1    (hwtcon_device_info()->mmsys_reg_pa + 0x4F04)
#define WF_LUT_MOUT                (hwtcon_device_info()->mmsys_reg_pa + 0x4F08)
#define WF_LUT_ADDR_0              (hwtcon_device_info()->mmsys_reg_pa + 0x4F10)
#define WF_LUT_ADDR_1              (hwtcon_device_info()->mmsys_reg_pa + 0x4F14)
#define WF_LUT_ADDR_2              (hwtcon_device_info()->mmsys_reg_pa + 0x4F18)
#define WF_LUT_ADDR_3              (hwtcon_device_info()->mmsys_reg_pa + 0x4F1C)
#define WF_LUT_ADDR_4              (hwtcon_device_info()->mmsys_reg_pa + 0x4F20)
#define WF_LUT_ADDR_5              (hwtcon_device_info()->mmsys_reg_pa + 0x4F24)
#define WF_LUT_ADDR_6              (hwtcon_device_info()->mmsys_reg_pa + 0x4F28)
#define WF_LUT_ADDR_7              (hwtcon_device_info()->mmsys_reg_pa + 0x4F2C)
#define WF_LUT_ADDR_8              (hwtcon_device_info()->mmsys_reg_pa + 0x4F30)
#define WF_LUT_ADDR_9              (hwtcon_device_info()->mmsys_reg_pa + 0x4F34)
#define WF_LUT_ADDR_10             (hwtcon_device_info()->mmsys_reg_pa + 0x4F38)
#define WF_LUT_ADDR_11             (hwtcon_device_info()->mmsys_reg_pa + 0x4F3C)
#define WF_LUT_ADDR_12             (hwtcon_device_info()->mmsys_reg_pa + 0x4F50)
#define WF_LUT_ADDR_13             (hwtcon_device_info()->mmsys_reg_pa + 0x4F54)
#define WF_LUT_ADDR_14             (hwtcon_device_info()->mmsys_reg_pa + 0x4F58)
#define WF_LUT_ADDR_15             (hwtcon_device_info()->mmsys_reg_pa + 0x4F5C)


#define WF_LUT_CRC_ID_SEL_0        (hwtcon_device_info()->mmsys_reg_pa + 0x42a0)
#define WF_LUT_CRC_ID_SEL_1        (hwtcon_device_info()->mmsys_reg_pa + 0x42a4)
#define WF_LUT_CRC_ID_SEL_2        (hwtcon_device_info()->mmsys_reg_pa + 0x42a8)
#define WF_LUT_CRC_ID_SEL_3        (hwtcon_device_info()->mmsys_reg_pa + 0x42ac)

/* WF_LUT_RDMA: 0x14005000 */
#define WF_LUT_RDMA_INT_ENABLE     (hwtcon_device_info()->mmsys_reg_pa + 0x5000)
#define WF_LUT_RDMA_INT_STATUS     (hwtcon_device_info()->mmsys_reg_pa + 0x5004)
#define WF_LUT_RDMA_INT_STATUS_VA  (hwtcon_device_info()->mmsys_reg_va + 0x5004)
#define WF_LUT_RDMA_GLOBAL_CON     (hwtcon_device_info()->mmsys_reg_pa + 0x5010)
#define WF_LUT_RDMA_SIZE_CON_0     (hwtcon_device_info()->mmsys_reg_pa + 0x5014)
#define WF_LUT_RDMA_SIZE_CON_1     (hwtcon_device_info()->mmsys_reg_pa + 0x5018)
#define WF_LUT_RDMA_TARGET_LINE    (hwtcon_device_info()->mmsys_reg_pa + 0x501c)
#define WF_LUT_RDMA_MEM_CON        (hwtcon_device_info()->mmsys_reg_pa + 0x5024)
#define WF_LUT_RDMA_MEM_SRC_PITCH  (hwtcon_device_info()->mmsys_reg_pa + 0x502C)
#define WF_LUT_RDMA_MEM_GMC_SETTING_0 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x5030)
#define WF_LUT_RDMA_MEM_SLOW_CON   (hwtcon_device_info()->mmsys_reg_pa + 0x5034)
#define WF_LUT_RDMA_MEM_GMC_SETTING_1 \
				(hwtcon_device_info()->mmsys_reg_pa + 0x5038)
#define WF_LUT_RDMA_FIFO_CON       (hwtcon_device_info()->mmsys_reg_pa + 0x5040)
#define WF_LUT_RDMA_FIFO_LOG       (hwtcon_device_info()->mmsys_reg_pa + 0x5044)
#define WF_LUT_RDMA_DUMMY          (hwtcon_device_info()->mmsys_reg_pa + 0x5090)
#define WF_LUT_RDMA_DEBUG_OUT_SEL  (hwtcon_device_info()->mmsys_reg_pa + 0x5094)
#define WF_LUT_RDMA_MEM_START_ADDR (hwtcon_device_info()->mmsys_reg_pa + 0x5F00)
#define WF_LUT_RDMA_BG_CON_0       (hwtcon_device_info()->mmsys_reg_pa + 0x50a0)
#define WF_LUT_RDMA_BG_CON_1       (hwtcon_device_info()->mmsys_reg_pa + 0x50a4)
#define WF_LUT_RDMA_THRESHOLD_FOR_SODI \
				(hwtcon_device_info()->mmsys_reg_pa + 0x50a8)

/* DPI: 0x14006000 */
#define WF_LUT_DPI_EN              (hwtcon_device_info()->mmsys_reg_pa + 0x6000)
#define WF_LUT_DPI_RST             (hwtcon_device_info()->mmsys_reg_pa + 0x6004)
#define WF_LUT_DPI_INTEN           (hwtcon_device_info()->mmsys_reg_pa + 0x6008)
#define WF_LUT_DPI_INTSTA          (hwtcon_device_info()->mmsys_reg_pa + 0x600C)
#define WF_LUT_DPI_INTSTA_VA       (hwtcon_device_info()->mmsys_reg_va + 0x600C)
#define WF_LUT_DPI_OUTPUT_SETTING  (hwtcon_device_info()->mmsys_reg_pa + 0x6014)
#define WF_LUT_DPI_SIZE            (hwtcon_device_info()->mmsys_reg_pa + 0x6018)
#define WF_LUT_DPI_TGEN_HWIDTH     (hwtcon_device_info()->mmsys_reg_pa + 0x6020)
#define WF_LUT_DPI_TGEN_HPORCH     (hwtcon_device_info()->mmsys_reg_pa + 0x6024)
#define WF_LUT_DPI_TGEN_VWIDTH     (hwtcon_device_info()->mmsys_reg_pa + 0x6028)
#define WF_LUT_DPI_TGEN_VPORCH     (hwtcon_device_info()->mmsys_reg_pa + 0x602C)
#define WF_LUT_DPI_STATUS          (hwtcon_device_info()->mmsys_reg_pa + 0x6040)
#define WF_LUT_DPI_STATUS_VA       (hwtcon_device_info()->mmsys_reg_va + 0x6040)

#define WF_LUT_DPI_TMODE           (hwtcon_device_info()->mmsys_reg_pa + 0x6044)
#define WF_LUT_DPI_CHECKSUM        (hwtcon_device_info()->mmsys_reg_pa + 0x6048)
#define WF_LUT_DPI_CHECKSUM_VA     (hwtcon_device_info()->mmsys_reg_va + 0x6048)
#define WF_LUT_DPI_MUTEX_VSYNC_SETTING \
			(hwtcon_device_info()->mmsys_reg_pa + 0x60E0)


/* TCON: 0x14007000        */
#define TCON_GR0                   (hwtcon_device_info()->mmsys_reg_pa + 0x7000)
#define TCON_GR1                   (hwtcon_device_info()->mmsys_reg_pa + 0x7004)
#define TCON_GR2                   (hwtcon_device_info()->mmsys_reg_pa + 0x7008)
#define TCON_GR3                   (hwtcon_device_info()->mmsys_reg_pa + 0x700C)
#define TCON_TIM0R0                (hwtcon_device_info()->mmsys_reg_pa + 0x7040)
#define TCON_TIM0R1                (hwtcon_device_info()->mmsys_reg_pa + 0x7044)
#define TCON_TIM0R2                (hwtcon_device_info()->mmsys_reg_pa + 0x7048)
#define TCON_TIM0R3                (hwtcon_device_info()->mmsys_reg_pa + 0x704C)
#define TCON_TIM0R4                (hwtcon_device_info()->mmsys_reg_pa + 0x7050)
#define TCON_TIM0R5                (hwtcon_device_info()->mmsys_reg_pa + 0x7054)
#define TCON_TIM0R6                (hwtcon_device_info()->mmsys_reg_pa + 0x7058)
#define TCON_TIM0R7                (hwtcon_device_info()->mmsys_reg_pa + 0x705C)
#define TCON_TIM1R0                (hwtcon_device_info()->mmsys_reg_pa + 0x7060)
#define TCON_TIM1R1                (hwtcon_device_info()->mmsys_reg_pa + 0x7064)
#define TCON_TIM1R2                (hwtcon_device_info()->mmsys_reg_pa + 0x7068)
#define TCON_TIM1R3                (hwtcon_device_info()->mmsys_reg_pa + 0x706C)
#define TCON_TIM1R4                (hwtcon_device_info()->mmsys_reg_pa + 0x7070)
#define TCON_TIM1R5                (hwtcon_device_info()->mmsys_reg_pa + 0x7074)
#define TCON_TIM1R6                (hwtcon_device_info()->mmsys_reg_pa + 0x7078)
#define TCON_TIM1R7                (hwtcon_device_info()->mmsys_reg_pa + 0x707C)
#define TCON_TIM2R0                (hwtcon_device_info()->mmsys_reg_pa + 0x7080)
#define TCON_TIM2R1                (hwtcon_device_info()->mmsys_reg_pa + 0x7084)
#define TCON_TIM2R2                (hwtcon_device_info()->mmsys_reg_pa + 0x7088)
#define TCON_TIM2R3                (hwtcon_device_info()->mmsys_reg_pa + 0x708C)
#define TCON_TIM2R4                (hwtcon_device_info()->mmsys_reg_pa + 0x7090)
#define TCON_TIM2R5                (hwtcon_device_info()->mmsys_reg_pa + 0x7094)
#define TCON_TIM2R6                (hwtcon_device_info()->mmsys_reg_pa + 0x7098)
#define TCON_TIM2R7                (hwtcon_device_info()->mmsys_reg_pa + 0x709C)
#define TCON_TIM3R0                (hwtcon_device_info()->mmsys_reg_pa + 0x70A0)
#define TCON_TIM3R1                (hwtcon_device_info()->mmsys_reg_pa + 0x70A4)
#define TCON_TIM3R2                (hwtcon_device_info()->mmsys_reg_pa + 0x70A8)
#define TCON_TIM3R3                (hwtcon_device_info()->mmsys_reg_pa + 0x70AC)
#define TCON_TIM3R4                (hwtcon_device_info()->mmsys_reg_pa + 0x70B0)
#define TCON_TIM3R5                (hwtcon_device_info()->mmsys_reg_pa + 0x70B4)
#define TCON_TIM3R6                (hwtcon_device_info()->mmsys_reg_pa + 0x70B8)
#define TCON_TIM3R7                (hwtcon_device_info()->mmsys_reg_pa + 0x70BC)
#define TCON_TIM4R0                (hwtcon_device_info()->mmsys_reg_pa + 0x70C0)
#define TCON_TIM4R1                (hwtcon_device_info()->mmsys_reg_pa + 0x70C4)
#define TCON_TIM4R2                (hwtcon_device_info()->mmsys_reg_pa + 0x70C8)
#define TCON_TIM4R3                (hwtcon_device_info()->mmsys_reg_pa + 0x70CC)
#define TCON_TIM4R4                (hwtcon_device_info()->mmsys_reg_pa + 0x70D0)
#define TCON_TIM4R5                (hwtcon_device_info()->mmsys_reg_pa + 0x70D4)
#define TCON_TIM4R6                (hwtcon_device_info()->mmsys_reg_pa + 0x70D8)
#define TCON_TIM4R7                (hwtcon_device_info()->mmsys_reg_pa + 0x70DC)
#define TCON_TIM5R0                (hwtcon_device_info()->mmsys_reg_pa + 0x70E0)
#define TCON_TIM5R1                (hwtcon_device_info()->mmsys_reg_pa + 0x70E4)
#define TCON_TIM5R2                (hwtcon_device_info()->mmsys_reg_pa + 0x70E8)
#define TCON_TIM5R3                (hwtcon_device_info()->mmsys_reg_pa + 0x70EC)
#define TCON_TIM5R4                (hwtcon_device_info()->mmsys_reg_pa + 0x70F0)
#define TCON_TIM5R5                (hwtcon_device_info()->mmsys_reg_pa + 0x70F4)
#define TCON_TIM5R6                (hwtcon_device_info()->mmsys_reg_pa + 0x70F8)
#define TCON_TIM5R7                (hwtcon_device_info()->mmsys_reg_pa + 0x70FC)
#define TCON_TIM6R0                (hwtcon_device_info()->mmsys_reg_pa + 0x7100)
#define TCON_TIM6R1                (hwtcon_device_info()->mmsys_reg_pa + 0x7104)
#define TCON_TIM6R2                (hwtcon_device_info()->mmsys_reg_pa + 0x7108)
#define TCON_TIM6R3                (hwtcon_device_info()->mmsys_reg_pa + 0x710C)
#define TCON_TIM6R4                (hwtcon_device_info()->mmsys_reg_pa + 0x7110)
#define TCON_TIM6R5                (hwtcon_device_info()->mmsys_reg_pa + 0x7114)
#define TCON_TIM6R6                (hwtcon_device_info()->mmsys_reg_pa + 0x7118)
#define TCON_TIM6R7                (hwtcon_device_info()->mmsys_reg_pa + 0x711C)
#define TCON_TIM7R0                (hwtcon_device_info()->mmsys_reg_pa + 0x7120)
#define TCON_TIM7R1                (hwtcon_device_info()->mmsys_reg_pa + 0x7124)
#define TCON_TIM7R2                (hwtcon_device_info()->mmsys_reg_pa + 0x7128)
#define TCON_TIM7R3                (hwtcon_device_info()->mmsys_reg_pa + 0x712C)
#define TCON_TIM7R4                (hwtcon_device_info()->mmsys_reg_pa + 0x7130)
#define TCON_TIM7R5                (hwtcon_device_info()->mmsys_reg_pa + 0x7134)
#define TCON_TIM7R6                (hwtcon_device_info()->mmsys_reg_pa + 0x7138)
#define TCON_TIM7R7                (hwtcon_device_info()->mmsys_reg_pa + 0x713C)

/* MMSYS: 0x14000000*/
#define MMSYS_CG_CON0              (hwtcon_device_info()->mmsys_reg_pa + 0x0100)
#define MMSYS_DUMMY1               (hwtcon_device_info()->mmsys_reg_pa + 0x0404)
#define MMSYS_MDP_DL_CFG_WD        (hwtcon_device_info()->mmsys_reg_pa + 0x0934)

#define WDMA_DST_ADDR0_VA         (hwtcon_device_info()->imgsys_reg_va + 0x6F00)
#define WDMA_DST_W_IN_BYTE_VA     (hwtcon_device_info()->imgsys_reg_va + 0x6028)


/* pipelien reg */
#define PAPER_TCTOP_PWDC_CTL_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD000)
#define PAPER_TCTOP_MAIN_CTL_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD004)
#define PAPER_TCTOP_INI_CFG_VA     (hwtcon_device_info()->mmsys_reg_va + 0xD008)
#define PAPER_TCTOP_PANEL_SIZE_VA  (hwtcon_device_info()->mmsys_reg_va + 0xD00C)
#define PAPER_TCTOP_REGAL_CFG_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD010)
#define PAPET_TCTOP_FIFO_CFG_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD014)
#define PAPER_TCTOP_DPI_CFG_VA     (hwtcon_device_info()->mmsys_reg_va + 0xD018)
#define PAPER_TCTOP_UPD_CFG0_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD020)
#define PAPER_TCTOP_UPD_CFG1_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD024)
#define PAPER_TCTOP_UPD_CFG2_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD028)
#define PAPER_TCTOP_UPD_CFG3_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD02C)
#define PAPER_TCTOP_UPD_CFG4_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD030)
#define PAPER_TCTOP_VOID_LUT_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD034)
#define PAPER_TCTOP_SOF_CTL_VA     (hwtcon_device_info()->mmsys_reg_va + 0xD040)
#define PAPER_TCTOP_IRQ_CTL_VA     (hwtcon_device_info()->mmsys_reg_va + 0xD044)
#define PAPER_TCTOP_SOF_MERGE_CTL_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD048)
#define PAPER_TCTOP_SOF_WF_LUT_CTL_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD04C)
#define PAPER_TCTOP_IMG_POS0_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD050)
#define PAPER_TCTOP_IMG_POS1_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD054)
#define PAPER_TCTOP_IMG_ID_VA      (hwtcon_device_info()->mmsys_reg_va + 0xD058)
#define PAPER_TCTOP_BUF_CFG0_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD060)
#define PAPER_TCTOP_BUF_CFG1_VA    (hwtcon_device_info()->mmsys_reg_va + 0xD064)
#define PAPER_TCTOP_HIST_CFG0_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD070)
#define PAPER_TCTOP_HIST_CFG1_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD074)
#define PAPER_TCTOP_HIST_CFG2_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD078)
#define PAPER_TCTOP_HIST_CFG3_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD07C)
#define PAPER_TCTOP_HIST_CFG4_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD080)
#define PAPER_TCTOP_HIST_STA0_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD084)
#define PAPER_TCTOP_HIST_STA1_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD088)
#define PAPER_TCTOP_HIST_STA2_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD08C)
#define PAPER_TCTOP_STATUS_VA      (hwtcon_device_info()->mmsys_reg_va + 0xD090)
#define PAPER_UPD_IMG_STA0_VA      (hwtcon_device_info()->mmsys_reg_va + 0xD094)
#define PAPER_UPD_IMG_STA1_VA      (hwtcon_device_info()->mmsys_reg_va + 0xD098)
#define PAPER_TCTOP_PIN_SWAP0_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0A0)
#define PAPER_TCTOP_PIN_SWAP1_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0A4)
#define PAPER_TCTOP_PIN_SWAP2_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0A8)
#define PAPER_TCTOP_PIN_SWAP3_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0AC)
#define PAPER_TCTOP_PIN_SWAP4_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0B0)
#define PAPER_TCTOP_PIN_SWAP5_VA   (hwtcon_device_info()->mmsys_reg_va + 0xD0B4)
#define PAPER_TCTOP_PIN_INV_VA     (hwtcon_device_info()->mmsys_reg_va + 0xD0B8)
#define PAPER_TCTOP_WB_BUF_XY_INFO_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0C4)
#define PAPER_TCTOP_WB_BUF_WH_INFO_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0C8)
#define PAPER_TCTOP_LUT_ACTIVE0_VA (hwtcon_device_info()->mmsys_reg_va + 0xD0D0)
#define PAPER_TCTOP_LUT_ACTIVE1_VA (hwtcon_device_info()->mmsys_reg_va + 0xD0D4)
#define PAPER_TCTOP_COL_STATUS0_VA (hwtcon_device_info()->mmsys_reg_va + 0xD0D8)
#define PAPER_TCTOP_COL_STATUS1_VA (hwtcon_device_info()->mmsys_reg_va + 0xD0DC)
#define PAPER_TCTOP_PXL_UPD_RGN0_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0E0)
#define PAPER_TCTOP_PXL_UPD_RGN1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0E4)
#define PAPER_TCTOP_PXL_COL_RGN0_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0E8)
#define PAPER_TCTOP_PXL_COL_RGN1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0xD0EC)
#define PAPER_TCTOP_WB_ST_ADDR0_VA (hwtcon_device_info()->mmsys_reg_va + 0xDF00)
#define PAPER_TCTOP_WB_ST_ADDR1_VA (hwtcon_device_info()->mmsys_reg_va + 0xDF04)
#define PAPER_TCTOP_IMG_ST_ADDR_VA (hwtcon_device_info()->mmsys_reg_va + 0xDF08)
#define PIPELINE_FLAG_VA           (hwtcon_device_info()->mmsys_reg_va + 0xDF0C)

/* IMG_RDMA */
#define IMG_RDMA_GLOBAL_CON_VA     (hwtcon_device_info()->mmsys_reg_va + 0x8010)
#define IMG_RDMA_FIFO_CON_VA       (hwtcon_device_info()->mmsys_reg_va + 0x8040)


/* WB RDMA */
#define WB_RDMA_GLOBAL_CON_VA      (hwtcon_device_info()->mmsys_reg_va + 0x9010)
#define WB_RDMA_FIFO_CON_VA        (hwtcon_device_info()->mmsys_reg_va + 0x9040)


/* WB_WDMA */
#define WB_WDMA_INTEN_VA           (hwtcon_device_info()->mmsys_reg_va + 0xA000)
#define WB_WDMA_INTSTA_VA          (hwtcon_device_info()->mmsys_reg_va + 0xA004)
#define WB_WDMA_EN_VA              (hwtcon_device_info()->mmsys_reg_va + 0xA008)
#define WB_WDMA_RST_VA             (hwtcon_device_info()->mmsys_reg_va + 0xA010)
#define WB_WDMA_CFG_VA             (hwtcon_device_info()->mmsys_reg_va + 0xA014)
#define WB_WDMA_BUF_CON1_VA        (hwtcon_device_info()->mmsys_reg_va + 0xA038)

/* WF_LUT */
#define WF_LUT_STA_VA              (hwtcon_device_info()->mmsys_reg_va + 0x4000)
#define WF_LUT_INTEN_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4004)
#define WF_LUT_INTSTA_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4008)
#define WF_LUT_EN_VA               (hwtcon_device_info()->mmsys_reg_va + 0x400C)
#define WF_LUT_TRIG_VA             (hwtcon_device_info()->mmsys_reg_va + 0x4010)
#define WF_LUT_RST_VA              (hwtcon_device_info()->mmsys_reg_va + 0x4014)
#define WF_LUT_ROI_SIZE_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4020)
#define WF_LUT_DATAPATH_CON_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4024)
#define WF_LUT_SRC_CON_VA          (hwtcon_device_info()->mmsys_reg_va + 0x402C)
#define WF_LUT_L0_CON_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4030)
#define WF_LUT_L0_SRC_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4038)
#define WF_LUT_L0_OFFSET_VA        (hwtcon_device_info()->mmsys_reg_va + 0x403C)
#define WF_LUT_L0_ADDR_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F40)
#define WF_LUT_L0_PITCH_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4044)
#define WF_LUT_L1_CON_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4050)
#define WF_LUT_L1_SRC_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4058)
#define WF_LUT_L1_OFFSET_VA        (hwtcon_device_info()->mmsys_reg_va + 0x405c)
#define WF_LUT_L1_ADDR_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F60)
#define WF_LUT_L1_PITCH_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4064)
#define WF_LUT_L2_CON_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4070)
#define WF_LUT_L2_SRC_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4078)
#define WF_LUT_L2_OFFSET_VA        (hwtcon_device_info()->mmsys_reg_va + 0x407c)
#define WF_LUT_L2_ADDR_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F80)
#define WF_LUT_L2_PITCH_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4084)
#define WF_LUT_L3_CON_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4090)
#define WF_LUT_L3_SRC_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4098)
#define WF_LUT_L3_OFFSET_VA        (hwtcon_device_info()->mmsys_reg_va + 0x409C)
#define WF_LUT_L3_ADDR_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4FA0)
#define WF_LUT_L3_PITCH_VA         (hwtcon_device_info()->mmsys_reg_va + 0x40A4)
#define WF_LUT_RDMA0_CTRL_VA       (hwtcon_device_info()->mmsys_reg_va + 0x40C0)
#define WF_LUT_RDMA0_MEM_GMC_SETTING1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x40C8)
#define WF_LUT_RDMA0_MEM_SLOW_CON_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x40CC)
#define WF_LUT_RDMA0_FIFO_CTRL_VA  (hwtcon_device_info()->mmsys_reg_va + 0x40D0)
#define WF_LUT_RDMA1_CTRL_VA       (hwtcon_device_info()->mmsys_reg_va + 0x40E0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x40E8)
#define WF_LUT_RDMA1_MEM_SLOW_CON_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x40EC)
#define WF_LUT_RDMA1_FIFO_CTRL_VA  (hwtcon_device_info()->mmsys_reg_va + 0x40F0)
#define WF_LUT_RDMA2_CTRL_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4100)
#define WF_LUT_RDMA2_MEM_GMC_SETTING1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x4108)
#define WF_LUT_RDMA2_MEM_SLOW_CON_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x410C)
#define WF_LUT_RDMA2_FIFO_CTRL_VA  (hwtcon_device_info()->mmsys_reg_va + 0x4110)
#define WF_LUT_RDMA3_CTRL_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4120)
#define WF_LUT_RDMA3_MEM_GMC_SETTING1_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x4128)
#define WF_LUT_RDMA3_MEM_SLOW_CON_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x412C)
#define WF_LUT_RDMA3_FIFO_CTRL_VA  (hwtcon_device_info()->mmsys_reg_va + 0x4130)
#define WF_LUT_DEBUG_MON_SEL_VA    (hwtcon_device_info()->mmsys_reg_va + 0x41D4)
#define WF_LUT_RDMA0_MEM_GMC_SETTING2_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x41E0)
#define WF_LUT_RDMA1_MEM_GMC_SETTING2_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x41E4)
#define WF_LUT_RDMA2_MEM_GMC_SETTING2_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x41E8)
#define WF_LUT_RDMA3_MEM_GMC_SETTING2_VA \
				(hwtcon_device_info()->mmsys_reg_va + 0x41EC)
#define WF_LUT_DUMMY_REG_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4200)
#define WF_LUT_FLOW_CTRL_DBG_VA    (hwtcon_device_info()->mmsys_reg_va + 0x4240)
#define WF_LUT_ADDCON_DBG_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4244)
#define WF_LUT_RDMA0_DBG_VA        (hwtcon_device_info()->mmsys_reg_va + 0x424C)
#define WF_LUT_RDMA1_DBG_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4250)
#define WF_LUT_RDMA2_DBG_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4254)
#define WF_LUT_RDMA3_DBG_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4258)
#define WF_LUT_EN_STA0_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4270)
#define WF_LUT_EN_STA1_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4274)


#define WF_LUT_SECURE_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4FC0)
#define WF_LUT_GREQ_LAYER_CNT_VA   (hwtcon_device_info()->mmsys_reg_va + 0x4234)
#define WF_LUT_SMI_DBG_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4230)
#define WF_LUT_00_XY_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4400)
#define WF_LUT_00_WH_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4404)
#define WF_LUT_00_ID_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4408)
#define WF_LUT_01_XY_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4410)
#define WF_LUT_01_WH_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4414)
#define WF_LUT_01_ID_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4418)
#define WF_LUT_63_XY_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4700)
#define WF_LUT_63_WH_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4704)
#define WF_LUT_63_ID_INFO_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4708)
#define WF_LUT_DUAL_MODE_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4D00)
#define WF_LUT_EN_0_VA             (hwtcon_device_info()->mmsys_reg_va + 0x4D04)
#define WF_LUT_EN_1_VA             (hwtcon_device_info()->mmsys_reg_va + 0x4D08)
#define WF_LUT_CON_VA              (hwtcon_device_info()->mmsys_reg_va + 0x4D0C)
#define WF_LUT_SHADOW_UP_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4204)
#define WF_LUT_LEN_0_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D10)
#define WF_LUT_LEN_1_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D14)
#define WF_LUT_LEN_2_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D18)
#define WF_LUT_LEN_3_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D1C)
#define WF_LUT_LEN_4_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D20)
#define WF_LUT_LEN_5_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D24)
#define WF_LUT_LEN_6_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D28)
#define WF_LUT_LEN_7_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D2C)
#define WF_LUT_LEN_8_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D30)
#define WF_LUT_LEN_9_VA            (hwtcon_device_info()->mmsys_reg_va + 0x4D34)
#define WF_LUT_LEN_10_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D38)
#define WF_LUT_LEN_11_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D3C)
#define WF_LUT_LEN_12_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D40)
#define WF_LUT_LEN_13_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D44)
#define WF_LUT_LEN_14_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D48)
#define WF_LUT_LEN_15_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4D4C)
#define WF_LUT_END_IRQ_CLR0_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D50)
#define WF_LUT_END_IRQ_CLR1_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D54)
#define WF_LUT_END_IRQ_STA0_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D58)
#define WF_LUT_END_IRQ_STA1_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D5C)
#define WF_LUT_CHKSUM_0_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4D70)
#define WF_LUT_CHKSUM_1_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4D74)
#define WF_LUT_CHKSUM_2_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4D78)
#define WF_LUT_CHKSUM_3_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4D7C)
#define WF_LUT_CHKSUM_4_VA         (hwtcon_device_info()->mmsys_reg_va + 0x4D80)
#define WF_LUT_LINK_MODE_VA        (hwtcon_device_info()->mmsys_reg_va + 0x4D84)
#define WF_LUT_TIMEOUT_CFG_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4D88)
#define WF_LUT_DEBUG_SRAM_VA       (hwtcon_device_info()->mmsys_reg_va + 0x4D8C)
#define WF_LUT_MERGE0_START_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D90)
#define WF_LUT_MERGE0_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4D94)
#define WF_LUT_MERGE1_START_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4D98)
#define WF_LUT_MERGE1_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4D9C)
#define WF_LUT_MERGE2_START_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4DA0)
#define WF_LUT_MERGE2_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DA4)
#define WF_LUT_MERGE3_START_VA     (hwtcon_device_info()->mmsys_reg_va + 0x4DA8)
#define WF_LUT_MERGE3_SIZE_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DAC)
#define WF_LUT_MERGE_POS_0_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DB0)
#define WF_LUT_MERGE_POS_1_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DB4)
#define WF_LUT_INFO_XY_CFG_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DC0)
#define WF_LUT_INFO_WH_CFG_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DC4)
#define WF_LUT_INFO_ID_CFG_VA      (hwtcon_device_info()->mmsys_reg_va + 0x4DC8)
#define WF_LUT_LINK_BASE_ADDR_VA   (hwtcon_device_info()->mmsys_reg_va + 0x4F00)
#define WF_LUT_LINK_BASE_ADDR_1_VA (hwtcon_device_info()->mmsys_reg_va + 0x4F04)
#define WF_LUT_MOUT_VA             (hwtcon_device_info()->mmsys_reg_va + 0x4F08)
#define WF_LUT_ADDR_0_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F10)
#define WF_LUT_ADDR_1_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F14)
#define WF_LUT_ADDR_2_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F18)
#define WF_LUT_ADDR_3_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F1C)
#define WF_LUT_ADDR_4_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F20)
#define WF_LUT_ADDR_5_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F24)
#define WF_LUT_ADDR_6_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F28)
#define WF_LUT_ADDR_7_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F2C)
#define WF_LUT_ADDR_8_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F30)
#define WF_LUT_ADDR_9_VA           (hwtcon_device_info()->mmsys_reg_va + 0x4F34)
#define WF_LUT_ADDR_10_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F38)
#define WF_LUT_ADDR_11_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F3C)
#define WF_LUT_ADDR_12_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F50)
#define WF_LUT_ADDR_13_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F54)
#define WF_LUT_ADDR_14_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F58)
#define WF_LUT_ADDR_15_VA          (hwtcon_device_info()->mmsys_reg_va + 0x4F5C)


#define WF_LUT_CRC_ID_SEL_0_VA     (hwtcon_device_info()->mmsys_reg_va + 0x42a0)
#define WF_LUT_CRC_ID_SEL_1_VA     (hwtcon_device_info()->mmsys_reg_va + 0x42a4)
#define WF_LUT_CRC_ID_SEL_2_VA     (hwtcon_device_info()->mmsys_reg_va + 0x42a8)
#define WF_LUT_CRC_ID_SEL_3_VA     (hwtcon_device_info()->mmsys_reg_va + 0x42ac)


#endif /* __HWTCON_REG_H__ */
