//
// Definitions for 5-Way Switch 5-way driver
//

#include <linux/input.h>

// 5-Way line enumeration
enum {
   UP_LINE = 0,
   DOWN_LINE,
   LEFT_LINE,
   RIGHT_LINE,
   SELECT_LINE
};

// Function that returns the IRQ number for a given 5-Way line
extern int fiveway_get_irq(int);

// IRQ definitions, only for those inputs that generate interrupts
#define FIVEWAY_UP_IRQ      fiveway_get_irq(UP_LINE)
#define FIVEWAY_DOWN_IRQ    fiveway_get_irq(DOWN_LINE)
#define FIVEWAY_LEFT_IRQ    fiveway_get_irq(LEFT_LINE)
#define FIVEWAY_RIGHT_IRQ   fiveway_get_irq(RIGHT_LINE)
#define FIVEWAY_SELECT_IRQ  fiveway_get_irq(SELECT_LINE)

// Keycodes generated by fiveway events
#define FIVEWAY_KEYCODE_UP       KEY_UP
#define FIVEWAY_KEYCODE_DOWN     KEY_DOWN
#define FIVEWAY_KEYCODE_LEFT     KEY_LEFT
#define FIVEWAY_KEYCODE_RIGHT    KEY_RIGHT
#define FIVEWAY_KEYCODE_SELECT   KEY_F24

// Line states
#define NUM_OF_LINES 5
enum {
   LINE_ASSERTED,
   LINE_DEASSERTED,
   LINE_HELD,
};

// External function definitions
static int __init fiveway_init(void);
static void __exit fiveway_exit(void);
static irqreturn_t fiveway_irq(int irq, void *data, struct pt_regs *r);

extern int gpio_fiveway_active(void);
extern void gpio_fiveway_inactive(void);
