//
// Definitions for volume keys driver
//

#include <linux/input.h>

// Volume line enumeration
enum {
   VOL_UP_LINE,
   VOL_DOWN_LINE,
};

// Function that returns the IRQ number for a given 5-Way line
extern int volume_get_irq(int);

// IRQ definitions, only for those inputs that generate interrupts
#define VOL_UP_IRQ          volume_get_irq(VOL_UP_LINE)
#define VOL_DOWN_IRQ        volume_get_irq(VOL_DOWN_LINE)

// Keycodes generated by volume events
#define VOL_UP_KEYCODE          KEY_VOLUMEUP
#define VOL_DOWN_KEYCODE        KEY_VOLUMEDOWN

// Line states
#define NUM_OF_LINES 2
enum {
   LINE_ASSERTED,
   LINE_DEASSERTED,
   LINE_HELD,
};

// External function definitions
static int __init volume_init(void);
static void __exit volume_exit(void);
static irqreturn_t volume_irq(int irq, void *data, struct pt_regs *r);

extern int gpio_volume_active(void);
extern void gpio_volume_inactive(void);
