#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
mount -t proc proc /proc

mkdir -p /splash && cd splash
tar -xf /opt/diagnostics.tar.xz

mount -t devtmpfs devtmpfs dev
mount -t sysfs sysfs sys
mount -t proc proc proc

cp /opt/device /splash/opt/device

mount /dev/mmcblk0p3 /mnt &>/dev/null
FWVERSION=$(cat /mnt/opt/update/version 2>/dev/null)
if [ "$FWVERSION" != "" ]; then
	echo "$FWVERSION" > /splash/opt/inkbox-version
else
	echo "Not available" > /splash/opt/inkbox-version
fi

chroot /splash /opt/diagnostics
