#!/bin/sh

verify_checksum() {
	CHECKSUM=$(sha256sum "${PACKAGE}" | awk '{ print $1 }')
	if [ "${CHECKSUM}" == "${CHECKSUM_VERIFY}" ]; then
		return 0
	else
		return 1
	fi
}

SERVER="pkgs.kobox.fermino.me"
DEVICE=$(cat /opt/device 2>/dev/null)
VERSION=$(cat /mnt/opt/version 2>/dev/null)i
PACKAGE="${1}"
IS_CONNECTED=$(cat /tmp/wifi_connected 2>/dev/null)
if [ "${IS_CONNECTED}" != "true" ]; then
	return 1
else
	# Trying firmware relase checksums
	CHECKSUM_VERIFY=$(wget -O - "http://${SERVER}/keyserver/device/${DEVICE}/packages/${VERSION}/${PACKAGE}.sha256")
	# If not found, then try with KoBox checksums
	if [ ${?} != 0 ]; then
		CHECKSUM_VERIFY=$(wget -O - "http://${SERVER}/keyserver/device/${DEVICE}/packages/kobox/${PACKAGE}.sha256" 2>/dev/null)
		if [ ${?} != 0 ]; then
			return 127
		else
			verify_checksum "${PACKAGE}"
			exit ${?}
	else
		verify_checksum "${PACKAGE}"
		exit ${?}
	fi
fi
