#!/bin/sh

DEVELOPER_FLAG_RAW=$(dd if=/dev/mmcblk0 bs=256 skip=159746 count=1 status=none)
DEVELOPER_FLAG=${DEVELOPER_FLAG_RAW:0:4}
UID=$(dd if=/dev/mmcblk0 bs=256 skip=2 count=1 status=none)
if [ "$DEVELOPER_FLAG" == "true" ]; then
	echo
	echo "Validating developer key ..."
	mkdir -p /mnt/tmp/key
	DEVELOPER_KEY=$(dd if=/dev/mmcblk0 bs=256 skip=159748 count=1 status=none)
	dd if=/dev/mmcblk0 of=/mnt/tmp/key/key.dgst bs=256 skip=159750 count=1 status=none
	echo -n "$DEVELOPER_KEY" | busybox chroot /mnt "/usr/bin/openssl" "dgst" "-sha256" "-verify" "/opt/key/public.pem" "-signature" "/tmp/key/key.dgst" &>/dev/null
	if [ $? != 0 ]; then
		echo "No valid key found or key missing. Aborting!"
		rm -rf /mnt/tmp/key
		exit 1
	else
		echo "Found valid developer key."
		echo "Validating against UID ..."
		if [ "$DEVELOPER_KEY" != "$UID" ]; then
			echo "Developer key does NOT match UID! Aborting!"
			exit 1
		else
			echo "Developer key does match UID."
			mkdir -p /mnt/opt/developer/key
			losetup /dev/loop3 /opt/valid-devkey.sqsh
			mount -o ro,nosuid,nodev,noexec /dev/loop3 /mnt/opt/developer/key
			rm -rf /mnt/tmp/key
			echo -e "\033[0;36mThe door is open now; be careful what you let in.\033[0m"
			exit 0
		fi
	fi
else
	# No developer key found
	exit 127
fi
