#!/bin/sh

omega() {
	# Memento, homo, quia pulvis es, et in pulverem reverteris.
	# Final system rundown
	mount -o remount,ro /overlaymount-rootfs/mnt/rootfs/overlay &>/dev/null
	umount /overlaymount-rootfs/mnt/rootfs/overlay -l -f &>/dev/null
	umount /overlaymount-rootfs/mnt/rootfs/read -l -f &>/dev/null
	umount /overlaymount-rootfs/mnt/rootfs -l -f &>/dev/null
	umount /overlaymount-rootfs/mnt/rootfs-part -l -f &>/dev/null
	umount /overlaymount-rootfs/mnt -l -f &>/dev/null
	umount /overlaymount-rootfs/proc -l -f &>/dev/null
	umount /overlaymount-rootfs/dev -l -f &>/dev/null
	umount /overlaymount-rootfs/sys -l -f &>/dev/null
	umount /overlaymount-rootfs -l -f &>/dev/null
	umount /rootfs-part -l -f &>/dev/null
}

update_rootfs() {
	mv /overlaymount-rootfs/mnt/rootfs/overlay/tmp/rootfs/rootfs.squashfs /tmp
	sync
	omega
	mount -t ext4 -o nosuid,noexec,nodev /dev/mmcblk0p3 /rootfs-part
	sync
	mv /tmp/rootfs.squashfs /rootfs-part/rootfs.squashfs
	sync
	umount /rootfs-part
}

mkfifo /mnt/run/initrd-fifo
while true; do
	if read line < /mnt/run/initrd-fifo; then
		if [[ "$line" == "poweroff" ]]; then
			omega
			busybox poweroff
			exit 0
		elif [[ "$line" == "reboot" ]]; then
			omega
			busybox reboot
			exit 0
		elif [[ "$line" == "update_rootfs" ]]; then
			update_rootfs
			busybox reboot
		fi
	fi
done &
