#!/bin/sh

mount -t devtmpfs devtmpfs /dev
mount -t sysfs sysfs /sys
mount -t proc proc /proc

mkdir -p /splash && cd splash
tar -xf /opt/diagnostics.tar.xz
mount -t devtmpfs devtmpfs dev
mount -t sysfs sysfs sys
mount -t proc proc proc
chroot /splash /opt/diagnostics
