#
# make eInk
#

obj-$(CONFIG_FB_EINK_WAVEFORM)      += waveform/
obj-$(CONFIG_FB_EINK_LEGACY)        += legacy/
obj-$(CONFIG_FB_EINK_HAL)           += hal/

#
# only for testing!
#

obj-$(CONFIG_FB_EINK_HAL_BUILTIN)   += hal/
