#ifndef NTX_PADS_H //[
#define NTX_PADS_H


#if defined( _MX7D_ )//[

	#define UART_PAD_CTRL  (PAD_CTL_DSE_3P3V_49OHM | \
		PAD_CTL_PUS_PU100KOHM | PAD_CTL_HYS)

	#define USDHC_PAD_CTRL (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
		PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU47KOHM)

	#define ENET_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_98OHM)
	#define ENET_PAD_CTRL_MII  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_98OHM)

	#define ENET_RX_PAD_CTRL  (PAD_CTL_PUS_PU100KOHM | PAD_CTL_DSE_3P3V_98OHM)

	#define I2C_PAD_CTRL    (PAD_CTL_DSE_3P3V_32OHM | PAD_CTL_SRE_SLOW | \
		PAD_CTL_HYS | PAD_CTL_PUE | PAD_CTL_PUS_PU100KOHM)

	#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_PU100KOHM | \
		PAD_CTL_DSE_3P3V_49OHM)

	#define QSPI_PAD_CTRL	\
		(PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_PUE | PAD_CTL_PUS_PU47KOHM)

	#define SPI_PAD_CTRL (PAD_CTL_DSE_3P3V_49OHM | PAD_CTL_SRE_SLOW | PAD_CTL_HYS)

	#define EPDC_PAD_CTRL	0x0

#elif defined( _MX6ULL_ )//[

	#define EPDC_PAD_CTRL	0x0

	#define UART_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |		\
		PAD_CTL_DSE_40ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define USDHC_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_22K_UP  | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_80ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define USDHC_DAT3_CD_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE |	\
		PAD_CTL_PUS_100K_DOWN  | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_80ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define I2C_PAD_CTRL    (PAD_CTL_PKE | PAD_CTL_PUE |            \
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |               \
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS |			\
		PAD_CTL_ODE)

	#define ENET_PAD_CTRL  (PAD_CTL_PUS_100K_UP | PAD_CTL_PUE |     \
		PAD_CTL_SPEED_HIGH   |                                  \
		PAD_CTL_DSE_48ohm   | PAD_CTL_SRE_FAST)

	#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_PUE | \
		PAD_CTL_PKE | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm)

	#define MDIO_PAD_CTRL  (PAD_CTL_PUS_100K_UP | PAD_CTL_PUE |     \
		PAD_CTL_DSE_48ohm   | PAD_CTL_SRE_FAST | PAD_CTL_ODE)

	#define ENET_CLK_PAD_CTRL  (PAD_CTL_DSE_40ohm   | PAD_CTL_SRE_FAST)

	#define ENET_RX_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |          \
		PAD_CTL_SPEED_HIGH   | PAD_CTL_SRE_FAST)
	
	#define GPMI_PAD_CTRL0 (PAD_CTL_PKE | PAD_CTL_PUE | PAD_CTL_PUS_100K_UP)
	#define GPMI_PAD_CTRL1 (PAD_CTL_DSE_40ohm | PAD_CTL_SPEED_MED | \
			PAD_CTL_SRE_FAST)
	#define GPMI_PAD_CTRL2 (GPMI_PAD_CTRL0 | GPMI_PAD_CTRL1)

	#define WEIM_NOR_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE | \
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED | \
		PAD_CTL_DSE_40ohm   | PAD_CTL_SRE_FAST)

	#define SPI_PAD_CTRL (PAD_CTL_HYS |				\
		PAD_CTL_SPEED_MED |		\
		PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

	#define OTG_ID_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_47K_UP  | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_80ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)


	#define INPUT_PAD_CTRL    (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |		\
		PAD_CTL_DSE_40ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

#elif defined( _MX6SLL_ )//[
	#define UART_PAD_CTRL  (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |		\
		PAD_CTL_DSE_40ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define USDHC_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_22K_UP  | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_34ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define USDHC_PAD_CTRL_WP (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_100K_DOWN | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_80ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define I2C_PAD_CTRL    (PAD_CTL_PKE | PAD_CTL_PUE |            \
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |               \
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS |			\
		PAD_CTL_ODE)

	#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_PUE | \
		PAD_CTL_PKE | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm)

	#define OTG_ID_PAD_CTRL (PAD_CTL_PKE | PAD_CTL_PUE |		\
		PAD_CTL_PUS_47K_UP  | PAD_CTL_SPEED_LOW |		\
		PAD_CTL_DSE_80ohm   | PAD_CTL_SRE_FAST  | PAD_CTL_HYS)

	#define SPI_PAD_CTRL (PAD_CTL_HYS | PAD_CTL_SPEED_MED | \
		PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

	#define LCD_PAD_CTRL    (PAD_CTL_HYS | PAD_CTL_PUS_100K_UP | PAD_CTL_PUE | \
		PAD_CTL_PKE | PAD_CTL_SPEED_MED | PAD_CTL_DSE_40ohm)

	#define EPDC_PAD_CTRL    (PAD_CTL_PKE | PAD_CTL_SPEED_MED |	\
		PAD_CTL_DSE_40ohm | PAD_CTL_SRE_FAST)

	#define INPUT_PAD_CTRL    (PAD_CTL_PKE | PAD_CTL_PUE |            \
		PAD_CTL_PUS_100K_UP | PAD_CTL_SPEED_MED |               \
		PAD_CTL_DSE_40ohm | PAD_CTL_HYS |			\
		PAD_CTL_ODE)

#if 1
	#define LED_PAD_CTRL    (NO_PAD_CTRL)
#else
	#define LED_PAD_CTRL    (PAD_CTL_HYS|PAD_CTL_PUS_47K_UP|PAD_CTL_PUE|PAD_CTL_PKE| \
		PAD_CTL_SPEED_LOW |PAD_CTL_DSE_80ohm |PAD_CTL_SRE_FAST)
#endif

#endif //] _MX7D_


#endif //]NTX_PADS_H


